// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcvinqtjzcikqsudqxkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdmlucXRqemNpa3FzdWRxeGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODgxNTcsImV4cCI6MjA2OTA2NDE1N30.d1c9p1e3CNuKHYLBhlFeQN2HeYWCdcXky6Mc0RBT0_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});